# Remove this line if you want to link your dependencies statically
use_frameworks!

target 'Sample' do
  pod 'Alamofire'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'lottie-ios'
  pod 'Dwifft'
  pod 'ReSwift'
  pod 'Changeset'
  pod 'SwiftyJSON'
  pod 'ImagePicker'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Charts'
  pod 'Masonry'
  pod 'iCarousel'
  pod 'SVProgressHUD'
  pod 'Realm'
  pod 'Nimbus'
  pod 'FLEX'
  pod 'CocoaAsyncSocket'
  pod 'Facebook-iOS-SDK'
  pod 'JSONModel'
  pod 'Cartography'
  pod 'Dollar'
  pod 'ComponentKit'
  pod 'DeepLinkKit'
  pod 'HockeyKit'
  pod 'SwiftLint'
end
